default_language_version:
    python: python3
default_stages:
- commit
repos:
-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v2.0.4
    hooks:
    -   id: autopep8
        args:
        - -i
        - --max-line-length=100
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
    -   id: trailing-whitespace
        stages:
        - commit
    -   id: end-of-file-fixer
        stages:
        - commit
    -   id: check-merge-conflict
    -   id: double-quote-string-fixer
    -   id: check-byte-order-marker
    -   id: mixed-line-ending
        args:
        - --fix=lf
    -   id: flake8
        args:
        - --max-line-length=100
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v3.12.0
    hooks:
    -   id: reorder-python-imports
        args:
        - --application-directories=.:software
        - --py3-plus
-   repo: https://github.com/humitos/mirrors-autoflake.git
    rev: v1.1
    hooks:
    -   id: autoflake
        args:
        - --in-place
        - --remove-all-unused-imports
        - --remove-unused-variable
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
    -   id: mypy
        additional_dependencies:
        - types-requests
        args:
        - --ignore-missing-imports
        - --follow-imports=silent
-   repo: local
    hooks:
    -   id: check_dependencies
        name: check_dependencies
        entry: docker exec ecodev_app python3.11 -c "from ecodev_core import check_dependencies; from pathlib import Path;
            exit(not check_dependencies(Path('/app/app'), Path('/app/app/assets/dependencies.txt')))"
        language: system
