services:

  ecodev_app:
    command: uvicorn app.dash_app:server  --host 0.0.0.0 --port 80 --reload
    ports:
      - ${dash_app_port:-8050}:80
      - ${jupyter_port:-5000}:5000
    volumes:
      - ./tests:/app/tests

  ecodev_app_backend:
    ports:
      - ${app_port:-8000}:80
    command: uvicorn app.app:app --host 0.0.0.0 --port 80 --reload --forwarded-allow-ips='*' --proxy-headers

networks:
  traefik-network:
    external: false
