MANAGE_RIGHTS = 'manage-rights'
TABLE = 'table'
UPDATE_BTN = 'update-btn'
ADD_BTN = 'add-btn'

ADD_RIGHTS_MODAL_CONFIRM_BTN_ID = 'add-rights-modal-confirm-btn-id'
ADD_RIGHTS_MODAL_CANCEL_BTN_ID = 'add-rights-modal-cancel-btn-id'
ADD_RIGHTS_MODAL_ID = 'add-rights-modal-id'
INTERNAL_EXTERNAL_SWITCH_ID = 'internal-external-switch-id'
USERS_MULTISELECT_ID = 'users-tags-input-id'
ROLE_SELECT_ID = 'role-select-id'
MODULE_MULTISELECT_ID = 'module-multiselect-id'
ADD_RIGHTS_MODAL_ERROR_ID = 'add-rights-modal-error-id'
UPDATE_RIGHTS_ALERT_ID = 'update-rights-alert-id'

REMOVE_USER_CONFIRMATION_MODAL_ID = 'remove-user-confirmation-modal-id'
REMOVE_USER_CONFIRMATION_BUTTON_ID = 'remove-user-confirmation-button-id'
REMOVE_USER_CANCELLATION_BUTTON_ID = 'remove-user-cancellation-button-id'

DELETE_PROJECT_BUTTON_ID = 'delete-project-button-id'
DELETE_PROJECT_CONFIRMATION_MODAL_ID = 'delete-project-confirmation-modal-id'
DELETE_PROJECT_CONFIRMATION_BUTTON_ID = 'delete-project-confirmation-button-id'
DELETE_PROJECT_CONFIRMATION_VALUE_ID = 'delete-project-confirmation-valude-id'
DELETE_PROJECT_CANCELLATION_BUTTON_ID = 'delete-project-cancellation-button-id'
