LAYOUT_PAGE_URL = '/layouts'
SIMPLE_PAGE_URL = f'{LAYOUT_PAGE_URL}/simple-page'
LEFT_ASIDE_PAGE_URL = f'{LAYOUT_PAGE_URL}/left-aside'
RIGHT_ASIDE_PAGE_URL = f'{LAYOUT_PAGE_URL}/right-aside'
LEFT_RIGHT_ASIDE_PAGE_URL = f'{LAYOUT_PAGE_URL}/left-right-asides'
COLLAPSIBLE_ASIDE_PAGE_URL = f'{LAYOUT_PAGE_URL}/collapsible-aside'

SIMPLE_PAGE_ID = 'simple-page-id'
LEFT_ASIDE_PAGE_ID = 'left-aside-page-id'
RIGHT_ASIDE_PAGE_ID = 'right-aside-page-id'
LEFT_RIGHT_ASIDE_PAGE_ID = 'left-right-aside-page-id'
COLLAPSIBLE_ASIDE_PAGE_ID = 'collapsible-aside-page-id'

ASIDE_BUTTON_ID = 'aside-button-id'
OPEN_ASIDE_BUTTON_ID = 'open-filter-button-id'
CLOSE_ASIDE_BUTTON_ID = 'close-filter-button-id'
