---
app_name: EcoApp

authentication:
  algorithm: HS256
  access_token_expire_minutes: 1440 # 24hrs
  secret_key: null

database:
  db_port: 5432
  db_name: null
  db_host: null
  db_username: null
  db_password: null
  db_test_name: null

dash_settings:
  debug: true
  gunicorn_setup: false
