name: pipeline

on:
  push:
    paths-ignore:
      - 'badges/**'

jobs:
  test:
    name: code quality
    runs-on: ubuntu-latest
    env:
      GITHUB-ACTION: true
    services:
      postgres:
        image: postgres:14.2-alpine
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
          -e POSTGRES_PASSWORD=postgres
          -e POSTGRES_DB=postgres
          -e POSTGRES_USER=postgres
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v3

      - name: Build the Docker image
        run: |
          docker build . --file Dockerfile-dev --tag ecodev_app:latest

      - name: Test with UnitTest
        uses: addnab/docker-run-action@v3
        env:
          POSTGRES_HOST: postgres
        with:
          image: ecodev_app:latest
          options:
            -e secret_key=${{ secrets.SECRET_KEY }}
            -e USERAPI_user=${{ secrets.ECOAUTH_API_USER }}
            -e USERAPI_password=${{ secrets.ECOAUTH_API_PWD }}
            -e environment=preprod
            -v ${{github.workspace}}/tests:/app/tests
            -v ${{github.workspace}}/app:/app/app
            -v ${{github.workspace}}/.coveragerc:/app/.coveragerc
            -v ${{github.workspace}}/config:/app/config
          run: |
            python3 -m unittest discover 

      - name: build front end stack
        run: |
          touch .env
          echo environment=preprod > .env
          docker network create test
          docker compose -f docker-compose-test.yml up -d


      - name:
        run: |
          # ensure the postgres container created for the backend test is reachable for frontend test
          docker rename $(docker ps --format '{{.Names}}' | grep post ) postgres
          docker network connect test postgres


      - name: run frontend test
        run: docker exec ecodev_app python3 tests_frontend/test_selenium.py


      - name: Setup tmate session # allow to ssh into runner for debug purpose
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3
        timeout-minutes: 15
